{
    "name": "COYA Comptabilité analytique programmes",
    "summary": "Budgets par bailleur/programme/projet, lignes budgétaires, imputation des dépenses, prévisionnel vs réel, rapports bailleur",
    "version": "18.0.1.0.0",
    "author": "SENEGEL",
    "website": "https://coya.pro",
    "category": "COYA",
    "license": "LGPL-3",
    "depends": ["base", "coya_departments"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "report/rapport_bailleur_report.xml",
        "views/programme_views.xml",
        "views/projet_views.xml",
        "views/ligne_budgetaire_views.xml",
        "views/imputation_views.xml",
        "views/dossier_projet_financier_views.xml",
    ],
    "installable": True,
    "application": False,
}
