{
    "name": "COYA Présences – Extractions et rapports",
    "summary": "Extraction des présences, vue par jour, synthèse et export pour super-admin",
    "version": "18.0.1.0.0",
    "author": "SENEGEL",
    "website": "https://coya.pro",
    "category": "COYA",
    "license": "LGPL-3",
    "depends": ["hr", "coya_presence_policy"],
    "data": [
        "security/ir.model.access.csv",
        "views/presence_report_views.xml",
        "views/presence_day_views.xml",
        "wizard/presence_day_wizard_views.xml",
        "wizard/presence_update_week_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
}
