{
    "name": "COYA Politique de présence",
    "summary": "Paramètres 44 h/semaine, plafond 10 h/jour, défalcation si insuffisant ; contrainte cumul journalier",
    "version": "18.0.1.0.0",
    "author": "SENEGEL",
    "website": "https://coya.pro",
    "category": "COYA",
    "license": "LGPL-3",
    "depends": ["base", "hr", "coya_time_tracking", "hr_holidays"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/hr_employee_views.xml",
        "views/presence_day_views.xml",
        "views/presence_alerte_views.xml",
        "views/presence_sanction_views.xml",
    ],
    "installable": True,
    "application": False,
}
